<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Buku_besar_model extends CI_Model
{

    public $table = 'buku_besar';
    public $id = 'id';
    public $tanggal = 'tanggal';
    public $order = 'DESC';
    public $orderASC = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,uuid_buku_besar,tanggal,kode_akun,keterangan,kode,debet,kredit,saldo');
        $this->datatables->from('buku_besar');
        //add this line for join
        //$this->datatables->join('table2', 'buku_besar.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('buku_besar/read/$1'),'Read')." | ".anchor(site_url('buku_besar/update/$1'),'Update')." | ".anchor(site_url('buku_besar/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    // get all
    function get_all_sort_by_tanggal()
    {
        $this->db->order_by($this->tanggal, $this->order);
        $this->db->order_by($this->id, $this->orderASC);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('uuid_buku_besar', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('kode_akun', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('debet', $q);
	$this->db->or_like('kredit', $q);
	$this->db->or_like('saldo', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('uuid_buku_besar', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('kode_akun', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('debet', $q);
	$this->db->or_like('kredit', $q);
	$this->db->or_like('saldo', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        // $this->db->insert($this->table, $data);


        // $this->db->set('uuid_spop', "replace(uuid(),'-','')", FALSE);
        $this->db->set('uuid_buku_besar', "replace(uuid(),'-','')", FALSE);
        $this->db->insert($this->table, $data);

        $datainsert = array(
            'PROCESS' => 'INSERT',
            'id' => $this->db->insert_id()
        );
        // print_r("<br/>");
        // print_r($datainsert['id']);
        // print_r("<br/>");
        // $this->db->where($this->id, $datainsert['id']);
        // $uuid_spop = $this->db->get($this->table)->row()->uuid_spop;
        // print_r($uuid_spop);

        // return $uuid_spop;

        // print_r($datainsert['id']);
        // die;

        return $datainsert['id'];

    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Buku_besar_model.php */
/* Location: ./application/models/Buku_besar_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-02-10 08:11:36 */
/* http://harviacode.com */