<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bukubank_model extends CI_Model
{

    public $table = 'bukubank';
    public $id = 'id';
    public $tanggal = 'tanggal';
    public $order = 'DESC';
    public $orderASC = 'SSC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,tanggal,bank,norek,keterangan,kode,debet,kredit,saldo');
        $this->datatables->from('bukubank');
        //add this line for join
        //$this->datatables->join('table2', 'bukubank.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('bukubank/read/$1'),'Read')." | ".anchor(site_url('bukubank/update/$1'),'Update')." | ".anchor(site_url('bukubank/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_sort_by_tanggal()
    {
        $this->db->order_by($this->tanggal, $this->orderASC);
        $this->db->order_by($this->id, $this->orderASC);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('bank', $q);
	$this->db->or_like('norek', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('debet', $q);
	$this->db->or_like('kredit', $q);
	$this->db->or_like('saldo', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('bank', $q);
	$this->db->or_like('norek', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('debet', $q);
	$this->db->or_like('kredit', $q);
	$this->db->or_like('saldo', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Bukubank_model.php */
/* Location: ./application/models/Bukubank_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-12-01 11:25:05 */
/* http://harviacode.com */