<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jurnal_kas_model extends CI_Model
{

    public $table = 'jurnal_kas';
    public $id = 'id';
    public $uuid_jurnal_kas = 'uuid_jurnal_kas';
    public $order = 'DESC';
    public $orderASC = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('nomor,tanggal,bukti,keterangan,kode_rekening,debet,kredit');
        $this->datatables->from('jurnal_kas');
        //add this line for join
        //$this->datatables->join('table2', 'jurnal_kas.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('jurnal_kas/read/$1'),'Read')." | ".anchor(site_url('jurnal_kas/update/$1'),'Update')." | ".anchor(site_url('jurnal_kas/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'nomor');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->tanggal, $this->orderASC);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    
    // get data by uuid_jurnal_kas
    function get_by_uuid_jurnal_kas($uuid_jurnal_kas)
    {
        $this->db->where($this->uuid_jurnal_kas, $uuid_jurnal_kas);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('nomor', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('bukti', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('kode_rekening', $q);
	$this->db->or_like('debet', $q);
	$this->db->or_like('kredit', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('nomor', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('bukti', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('kode_rekening', $q);
	$this->db->or_like('debet', $q);
	$this->db->or_like('kredit', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        // $this->db->insert($this->table, $data);

        $this->db->set('uuid_jurnal_kas', "replace(uuid(),'-','')", FALSE);
        $this->db->insert($this->table, $data);

        $datainsert = array(
            'PROCESS' => 'INSERT',
            'id' => $this->db->insert_id()
        );
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }
    // update data
    function update_kode_akun_per_uuid_jurnal_kas($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Jurnal_kas_model.php */
/* Location: ./application/models/Jurnal_kas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-12-01 11:32:21 */
/* http://harviacode.com */