<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jurnal_pengeluaran_kas_model extends CI_Model
{

    public $table = 'jurnal_pengeluaran_kas';
    public $id = 'nomor';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('nomor,tanggal,nomor_bukti_bkk,pl,keterangan,debet_21101uu_dagang,serba-serbi_nomor_rekening,serba_serbi_jumlah,kredit_11101_kas_besar');
        $this->datatables->from('jurnal_pengeluaran_kas');
        //add this line for join
        //$this->datatables->join('table2', 'jurnal_pengeluaran_kas.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('jurnal_pengeluaran_kas/read/$1'),'Read')." | ".anchor(site_url('jurnal_pengeluaran_kas/update/$1'),'Update')." | ".anchor(site_url('jurnal_pengeluaran_kas/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'nomor');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('nomor', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('nomor_bukti_bkk', $q);
	$this->db->or_like('pl', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('debet_21101uu_dagang', $q);
	$this->db->or_like('serba-serbi_nomor_rekening', $q);
	$this->db->or_like('serba_serbi_jumlah', $q);
	$this->db->or_like('kredit_11101_kas_besar', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('nomor', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('nomor_bukti_bkk', $q);
	$this->db->or_like('pl', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('debet_21101uu_dagang', $q);
	$this->db->or_like('serba-serbi_nomor_rekening', $q);
	$this->db->or_like('serba_serbi_jumlah', $q);
	$this->db->or_like('kredit_11101_kas_besar', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Jurnal_pengeluaran_kas_model.php */
/* Location: ./application/models/Jurnal_pengeluaran_kas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-12-01 11:37:03 */
/* http://harviacode.com */