<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jurnal_pembelian_model extends CI_Model
{

    public $table = 'jurnal_pembelian';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,tanggal,unit,spop,pl,supplier,norek,rekening,jumlah,uu21101');
        $this->datatables->from('jurnal_pembelian');
        //add this line for join
        //$this->datatables->join('table2', 'jurnal_pembelian.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('jurnal_pembelian/read/$1'),'Read')." | ".anchor(site_url('jurnal_pembelian/update/$1'),'Update')." | ".anchor(site_url('jurnal_pembelian/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('unit', $q);
	$this->db->or_like('spop', $q);
	$this->db->or_like('pl', $q);
	$this->db->or_like('supplier', $q);
	$this->db->or_like('norek', $q);
	$this->db->or_like('rekening', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('uu21101', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('unit', $q);
	$this->db->or_like('spop', $q);
	$this->db->or_like('pl', $q);
	$this->db->or_like('supplier', $q);
	$this->db->or_like('norek', $q);
	$this->db->or_like('rekening', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('uu21101', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Jurnal_pembelian_model.php */
/* Location: ./application/models/Jurnal_pembelian_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-12-01 11:32:28 */
/* http://harviacode.com */