<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jurnal_umum_model extends CI_Model
{

    public $table = 'jurnal_umum';
    public $id = 'nomor';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('nomor,tanggal,bukti,pl,ref,uraian_kode_rekening,rekening,debit,kredit');
        $this->datatables->from('jurnal_umum');
        //add this line for join
        //$this->datatables->join('table2', 'jurnal_umum.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('jurnal_umum/read/$1'),'Read')." | ".anchor(site_url('jurnal_umum/update/$1'),'Update')." | ".anchor(site_url('jurnal_umum/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'nomor');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('nomor', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('bukti', $q);
	$this->db->or_like('pl', $q);
	$this->db->or_like('ref', $q);
	$this->db->or_like('uraian_kode_rekening', $q);
	$this->db->or_like('rekening', $q);
	$this->db->or_like('debit', $q);
	$this->db->or_like('kredit', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('nomor', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('bukti', $q);
	$this->db->or_like('pl', $q);
	$this->db->or_like('ref', $q);
	$this->db->or_like('uraian_kode_rekening', $q);
	$this->db->or_like('rekening', $q);
	$this->db->or_like('debit', $q);
	$this->db->or_like('kredit', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Jurnal_umum_model.php */
/* Location: ./application/models/Jurnal_umum_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-12-01 11:40:37 */
/* http://harviacode.com */