<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Neraca_saldo_model extends CI_Model
{

    public $table = 'neraca_saldo';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,uuid_kode_akun,kode_akun,nama_akun,uraian,group,debet_akhir_tahun_lalu,kredit_akhir_tahun_lalu,debet_penyesuaian,kredit_penyesuaian,debet_ns_setelah_penyesuaian,kredit_ns_setelah_penyesuaian,debet_laba_rugi,kreditdebet_laba_rugi');
        $this->datatables->from('neraca_saldo');
        //add this line for join
        //$this->datatables->join('table2', 'neraca_saldo.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('neraca_saldo/read/$1'),'Read')." | ".anchor(site_url('neraca_saldo/update/$1'),'Update')." | ".anchor(site_url('neraca_saldo/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('uuid_kode_akun', $q);
	$this->db->or_like('kode_akun', $q);
	$this->db->or_like('nama_akun', $q);
	$this->db->or_like('uraian', $q);
	$this->db->or_like('group', $q);
	$this->db->or_like('debet_akhir_tahun_lalu', $q);
	$this->db->or_like('kredit_akhir_tahun_lalu', $q);
	$this->db->or_like('debet_penyesuaian', $q);
	$this->db->or_like('kredit_penyesuaian', $q);
	$this->db->or_like('debet_ns_setelah_penyesuaian', $q);
	$this->db->or_like('kredit_ns_setelah_penyesuaian', $q);
	$this->db->or_like('debet_laba_rugi', $q);
	$this->db->or_like('kreditdebet_laba_rugi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('uuid_kode_akun', $q);
	$this->db->or_like('kode_akun', $q);
	$this->db->or_like('nama_akun', $q);
	$this->db->or_like('uraian', $q);
	$this->db->or_like('group', $q);
	$this->db->or_like('debet_akhir_tahun_lalu', $q);
	$this->db->or_like('kredit_akhir_tahun_lalu', $q);
	$this->db->or_like('debet_penyesuaian', $q);
	$this->db->or_like('kredit_penyesuaian', $q);
	$this->db->or_like('debet_ns_setelah_penyesuaian', $q);
	$this->db->or_like('kredit_ns_setelah_penyesuaian', $q);
	$this->db->or_like('debet_laba_rugi', $q);
	$this->db->or_like('kreditdebet_laba_rugi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        // $this->db->insert($this->table, $data);

        $this->db->set('uuid_kode_akun', "replace(uuid(),'-','')", FALSE);
        $this->db->insert($this->table, $data);

        $datainsert = array(
            'PROCESS' => 'INSERT',
            'id' => $this->db->insert_id()
        );

    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Neraca_saldo_model.php */
/* Location: ./application/models/Neraca_saldo_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-02-12 07:32:35 */
/* http://harviacode.com */