<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sys_nama_barang_model extends CI_Model
{

    public $table = 'sys_nama_barang';
    public $id = 'id';
    public $uuid_barang = 'uuid_barang';
    public $nama_barang = 'nama_barang';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    // get data by id
    function get_by_nama_barang($nama_barang)
    {
        $this->db->where($this->nama_barang, $nama_barang);
        return $this->db->get($this->table)->row();
    }
    // get data by id
    function get_by_uuid_barang($uuid_barang)
    {
        $this->db->where($this->uuid_barang, $uuid_barang);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('uuid_barang', $q);
	$this->db->or_like('kode_barang', $q);
	$this->db->or_like('nama_barang', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('uuid_barang', $q);
	$this->db->or_like('kode_barang', $q);
	$this->db->or_like('nama_barang', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        // $this->db->insert($this->table, $data);

        $this->db->set('uuid_barang', "replace(uuid(),'-','')", FALSE);
        $this->db->insert($this->table, $data);

        $datainsert = array(
            'PROCESS' => 'INSERT',
            'id' => $this->db->insert_id()
        );

        return $datainsert['id'];
    }

    // insert data
    function insert_dari_pecah_satuan($data)
    {
        // $this->db->insert($this->table, $data);

        $this->db->set('uuid_barang', "replace(uuid(),'-','')", FALSE);
        $this->db->insert($this->table, $data);

        $datainsert = array(
            'PROCESS' => 'INSERT',
            'id' => $this->db->insert_id()
        );

        $this->db->where($this->id, $datainsert['id']);
        $uuid_barang = $this->db->get($this->table)->row()->uuid_barang;

        return $uuid_barang;

    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Sys_nama_barang_model.php */
/* Location: ./application/models/Sys_nama_barang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-09-11 15:47:14 */
/* http://harviacode.com */