<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_pembelian_pengajuan_bayar_model extends CI_Model
{

    public $table = 'tbl_pembelian_pengajuan_bayar';
    public $id = 'id';
    public $uuid_spop = 'uuid_spop';
    public $uuid_pengajuan_bayar = 'uuid_pengajuan_bayar';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data by id
    function get_by_uuid_spop($uuid_spop)
    {
        $this->db->where($this->uuid_spop, $uuid_spop);
        return $this->db->get($this->table)->result();
    }
    // get data by id
    function get_sumNominal_by_uuid_spop($uuid_spop)
    {
        // print_r($uuid_spop);
        // print_r("<br/>");
        // $this->db->where($this->uuid_spop, $uuid_spop);
        // return $this->db->get($this->table)->result();

        $sql = "SELECT tbl_pembelian_pengajuan_bayar_a.uuid_spop as uuid_spop, 
        sum(tbl_pembelian_pengajuan_bayar_a.nominal_pengajuan) as total_pengajuan
        
        FROM tbl_pembelian_pengajuan_bayar tbl_pembelian_pengajuan_bayar_a 
        
        -- group by tbl_pembelian_pengajuan_bayar_a.uuid_spop 
        WHERE tbl_pembelian_pengajuan_bayar_a.uuid_spop = '$uuid_spop'
        ";
       
    //    print_r($this->db->query($sql)->row());
    //    die;
        // return $this->db->query($sql)->row_array();
        return $this->db->query($sql)->row();


    }

    // get data by id
    function get_by_uuid_pengajuan_bayar($uuid_pengajuan_bayar)
    {
        $this->db->where($this->uuid_pengajuan_bayar, $uuid_pengajuan_bayar);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('proses_input', $q);
	$this->db->or_like('date_input', $q);
	$this->db->or_like('uuid_pengajuan_bayar', $q);
	$this->db->or_like('uuid_spop', $q);
	$this->db->or_like('tgl_pengajuan', $q);
	$this->db->or_like('nominal_pengajuan', $q);
	$this->db->or_like('id_usr', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('proses_input', $q);
	$this->db->or_like('date_input', $q);
	$this->db->or_like('uuid_pengajuan_bayar', $q);
	$this->db->or_like('uuid_spop', $q);
	$this->db->or_like('tgl_pengajuan', $q);
	$this->db->or_like('nominal_pengajuan', $q);
	$this->db->or_like('id_usr', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        // $this->db->insert($this->table, $data);

        
        $this->db->set('uuid_pengajuan_bayar', "replace(uuid(),'-','')", FALSE);
        $this->db->insert($this->table, $data);

        $datainsert = array(
            'PROCESS' => 'INSERT',
            'id' => $this->db->insert_id()
        );
        return $this->get_by_id($datainsert['id'])->uuid_pengajuan_bayar;

    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_pembelian_pengajuan_bayar_model.php */
/* Location: ./application/models/Tbl_pembelian_pengajuan_bayar_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-09-23 04:38:11 */
/* http://harviacode.com */