<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_saldo_bulanan_model extends CI_Model
{

    public $table = 'tbl_saldo_bulanan';
    public $id = 'id';
    public $tahun = 'tahun';
    public $bulan = 'bulan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

   function get_saldo_bulan_lalu($tahunpilih,$bulanpilih)
    {


       

        $tahunpilih=$tahunpilih;
        $bulanpilih=$bulanpilih;
        $bulanlalu=$bulanpilih-1;
        // $bulanlalu2=$bulanpilih-2;
        // $bulanlalu3=$bulanpilih-3;
        // $bulanlalu4=$bulanpilih-4;

// print_r($tahunpilih);
// print_r("<br/>");
// print_r($bulanpilih);
// print_r("<br/>");
// print_r($bulanlalu);
// print_r("<br/>");
// print_r($bulanlalu2);
// print_r("<br/>");
// print_r($bulanlalu3);
// print_r("<br/>");
// print_r($bulanlalu4);
// print_r("<br/>");
// print_r("<br/>");


        $sql = "SELECT sum(selisih) as saldo FROM panjar_db WHERE YEAR(tgl_panjar)=$tahunpilih AND MONTH(tgl_panjar) BETWEEN $bulanlalu AND $bulanlalu";
        $saldobulanLalu = $this->db->query($sql)->result();

//         $sql = "SELECT sum(selisih) as saldo FROM panjar_db WHERE YEAR(tgl_panjar)=$tahunpilih AND MONTH(tgl_panjar) BETWEEN $bulanlalu2 AND $bulanlalu2";
//         $saldobulanLalu2 = $this->db->query($sql)->result();

//         $sql = "SELECT sum(selisih) as saldo FROM panjar_db WHERE YEAR(tgl_panjar)=$tahunpilih AND MONTH(tgl_panjar) BETWEEN $bulanlalu3 AND $bulanlalu3";
//         $saldobulanLalu3 = $this->db->query($sql)->result();

//         $sql = "SELECT sum(selisih) as saldo FROM panjar_db WHERE YEAR(tgl_panjar)=$tahunpilih AND MONTH(tgl_panjar) BETWEEN $bulanlalu4 AND $bulanlalu4";
//         $saldobulanLalu4 = $this->db->query($sql)->result();

// print_r($saldobulanLalu);
// print_r("<br/>");
// print_r($saldobulanLalu2);
// print_r("<br/>");
// print_r($saldobulanLalu3);
// print_r("<br/>");
// print_r($saldobulanLalu4);
// print_r("<br/>");
// die;




        // $tahunsekarang=$tahunpilih;
        // $bulan_lalu=$bulanpilih-1;
        // $this->db->order_by($this->id, $this->order);
        // $this->db->where($this->tahun, $tahunsekarang);
        // $this->db->where($this->bulan, $bulan_lalu);
        // return $this->db->get($this->table)->row();

        return $this->db->query($sql)->row();

    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('bulan', $q);
	$this->db->or_like('saldo', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('bulan', $q);
	$this->db->or_like('saldo', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_saldo_bulanan_model.php */
/* Location: ./application/models/Tbl_saldo_bulanan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-22 20:50:01 */
/* http://harviacode.com */