<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_identitas_pengguna_model extends CI_Model
{

    public $table = 'tbl_identitas_pedagang_pasar';
    public $id = 'id';
    public $idpedagang = 'idpedagang';
    public $nik = 'nik';
    public $kodepasar = 'kodepasar';
    //public $idpedagang = 'idpedagang';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
		
	   $cek = $this->session->userdata('company');
		if($cek == 'pasar'){
			$kodepasar=$this->session->userdata('kodepasar');
			$this->db->order_by($this->id, $this->order);
			$this->db->where($this->kodepasar, $kodepasar);
		}else{		
			$this->db->order_by($this->id, $this->order);
		}
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id_pengguna($id)
    {

        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
   function get_by_id($idpedagang)
    {

        $this->db->where($this->idpedagang, $idpedagang);
        return $this->db->get($this->table)->row();
    }
    
    function get_by_id_penyewa($nik)
    {
        
        $this->db->where($this->nik, $nik);
        return $this->db->get($this->table)->row();
    }
	
	
    function get_by_nik($nik)
    {
        $this->db->where($this->nik, $nik);
        return $this->db->get($this->table)->row();
    }

	function get_by_nik_result($nik)
    {
        $this->db->where($this->nik, $nik);
        return $this->db->get($this->table)->result_array();
    }
    
    // get total rows
    function total_rows($q = NULL) {
    $this->db->like('id', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('idpedagang', $q);
    $this->db->or_like('nama', $q);
    $this->db->or_like('tempat_lahir', $q);
    $this->db->or_like('tgl_lahir', $q);
    $this->db->or_like('alamat', $q);
    $this->db->or_like('desa', $q);
    $this->db->or_like('kecamatan', $q);
    $this->db->or_like('kabupaten', $q);
    $this->db->or_like('propinsi', $q);
	$this->db->or_like('jeniskelamin', $q);
	$this->db->or_like('status', $q);
    $this->db->or_like('no_hp', $q);
    $this->db->or_like('npwp', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
    $this->db->order_by($this->id, $this->order);
    $this->db->like('id', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('idpedagang', $q);
    $this->db->or_like('nama', $q);
    $this->db->or_like('tempat_lahir', $q);
    $this->db->or_like('tgl_lahir', $q);
    $this->db->or_like('alamat', $q);
    $this->db->or_like('desa', $q);
    $this->db->or_like('kecamatan', $q);
    $this->db->or_like('kabupaten', $q);
    $this->db->or_like('propinsi', $q);
	$this->db->or_like('jeniskelamin', $q);
	$this->db->or_like('status', $q);
    $this->db->or_like('no_hp', $q);
    $this->db->or_like('npwp', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {

        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_identitas_pengguna_model.php */
/* Location: ./application/models/Tbl_identitas_pengguna_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-28 08:33:26 */
/* http://harviacode.com */