<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Tbl_penjualan_accounting_pembayaran_model extends CI_Model
{

	public $table = 'tbl_penjualan_accounting_pembayaran';
	public $id = 'id';
	public $order = 'DESC';

	function __construct()
	{
		parent::__construct();
	}

	// get all
	function get_all()
	{
		$this->db->order_by($this->id, $this->order);
		return $this->db->get($this->table)->result();
	}

	// get data by id
	function get_by_id($id)
	{
		$this->db->where($this->id, $id);
		return $this->db->get($this->table)->row();
	}

	// get total rows
	function total_rows($q = NULL)
	{
		$this->db->like('id', $q);
		$this->db->or_like('uuid_pembayaran', $q);
		$this->db->or_like('tgl_bayar', $q);
		$this->db->or_like('nominal_bayar', $q);
		$this->db->or_like('nmr_bukti_bayar', $q);
		$this->db->or_like('uuid_penjualan', $q);
		$this->db->or_like('uuid_barang', $q);
		$this->db->or_like('tgl_input', $q);
		$this->db->or_like('tgl_jual', $q);
		$this->db->or_like('nmrpesan', $q);
		$this->db->or_like('nmrkirim', $q);
		$this->db->or_like('uuid_konsumen', $q);
		$this->db->or_like('konsumen_id', $q);
		$this->db->or_like('konsumen_nama', $q);
		$this->db->or_like('kode_barang', $q);
		$this->db->or_like('nama_barang', $q);
		$this->db->or_like('uuid_unit', $q);
		$this->db->or_like('unit', $q);
		$this->db->or_like('satuan', $q);
		$this->db->or_like('harga_satuan', $q);
		$this->db->or_like('jumlah', $q);
		$this->db->or_like('total_nominal', $q);
		$this->db->or_like('umpphpsl22', $q);
		$this->db->or_like('piutang', $q);
		$this->db->or_like('penjualandpp', $q);
		$this->db->or_like('utangppn', $q);
		$this->db->or_like('uuid_kode_akun', $q);
		$this->db->or_like('kode_akun', $q);
		$this->db->or_like('nama_akun', $q);
		$this->db->or_like('id_usr', $q);
		$this->db->from($this->table);
		return $this->db->count_all_results();
	}

	// get data with limit and search
	function get_limit_data($limit, $start = 0, $q = NULL)
	{
		$this->db->order_by($this->id, $this->order);
		$this->db->like('id', $q);
		$this->db->or_like('uuid_pembayaran', $q);
		$this->db->or_like('tgl_bayar', $q);
		$this->db->or_like('nominal_bayar', $q);
		$this->db->or_like('nmr_bukti_bayar', $q);
		$this->db->or_like('uuid_penjualan', $q);
		$this->db->or_like('uuid_barang', $q);
		$this->db->or_like('tgl_input', $q);
		$this->db->or_like('tgl_jual', $q);
		$this->db->or_like('nmrpesan', $q);
		$this->db->or_like('nmrkirim', $q);
		$this->db->or_like('uuid_konsumen', $q);
		$this->db->or_like('konsumen_id', $q);
		$this->db->or_like('konsumen_nama', $q);
		$this->db->or_like('kode_barang', $q);
		$this->db->or_like('nama_barang', $q);
		$this->db->or_like('uuid_unit', $q);
		$this->db->or_like('unit', $q);
		$this->db->or_like('satuan', $q);
		$this->db->or_like('harga_satuan', $q);
		$this->db->or_like('jumlah', $q);
		$this->db->or_like('total_nominal', $q);
		$this->db->or_like('umpphpsl22', $q);
		$this->db->or_like('piutang', $q);
		$this->db->or_like('penjualandpp', $q);
		$this->db->or_like('utangppn', $q);
		$this->db->or_like('uuid_kode_akun', $q);
		$this->db->or_like('kode_akun', $q);
		$this->db->or_like('nama_akun', $q);
		$this->db->or_like('id_usr', $q);
		$this->db->limit($limit, $start);
		return $this->db->get($this->table)->result();
	}

	// insert data
	function insert($data)
	{

		// print_r($data);
		// print_r("<br/>");
		// print_r("<br/>");

		// $this->db->insert($this->table, $data);

		$this->db->set('uuid_pembayaran', "replace(uuid(),'-','')", FALSE);
		$this->db->insert($this->table, $data);

		$datainsert = array(
			'PROCESS' => 'INSERT',
			'id' => $this->db->insert_id()
		);


		// print_r($datainsert);
		// print_r("<br/>");
		// print_r("<br/>");
		// die;


		return ($datainsert);
	}

	// update data
	function update($id, $data)
	{
		$this->db->where($this->id, $id);
		$this->db->update($this->table, $data);
	}

	// delete data
	function delete($id)
	{
		$this->db->where($this->id, $id);
		$this->db->delete($this->table);
	}
}

/* End of file Tbl_penjualan_accounting_pembayaran_model.php */
/* Location: ./application/models/Tbl_penjualan_accounting_pembayaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-06-22 12:39:28 */
/* http://harviacode.com */