<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_hak_akses_model extends CI_Model
{

    public $table = 'tbl_hak_akses';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('id,id_user,id_user_level,main_menu,id_menu');
        $this->datatables->from('tbl_hak_akses');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_hak_akses.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('tbl_hak_akses/read/$1'), 'Read') . " | " . anchor(site_url('tbl_hak_akses/update/$1'), 'Update') . " | " . anchor(site_url('tbl_hak_akses/delete/$1'), 'Delete', 'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('id_user', $q);
        $this->db->or_like('id_user_level', $q);
        $this->db->or_like('main_menu', $q);
        $this->db->or_like('id_menu', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('id_user', $q);
        $this->db->or_like('id_user_level', $q);
        $this->db->or_like('main_menu', $q);
        $this->db->or_like('id_menu', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        // print_r("update");
        // print_r("<br/>");
        // print_r($id);
        // print_r("<br/>");
        // print_r($data);
        // print_r("<br/>");
        // die;

        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Tbl_hak_akses_model.php */
/* Location: ./application/models/Tbl_hak_akses_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-11-03 05:54:04 */
/* http://harviacode.com */