<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_accounting_group_model extends CI_Model
{

    public $table = 'tbl_accounting_group';
    public $id = 'id';
    public $uuid_group = 'uuid_group';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,uuid_group,nama_group,keterangan,id_usr');
        $this->datatables->from('tbl_accounting_group');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_accounting_group.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('tbl_accounting_group/read/$1'),'Read')." | ".anchor(site_url('tbl_accounting_group/update/$1'),'Update')." | ".anchor(site_url('tbl_accounting_group/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    

    // get data by id
    function get_by_uuid_group($uuid_group)
    {
        $this->db->where($this->uuid_group, $uuid_group);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('uuid_group', $q);
	$this->db->or_like('nama_group', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('id_usr', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('uuid_group', $q);
	$this->db->or_like('nama_group', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('id_usr', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        // $this->db->insert($this->table, $data);

        $this->db->set('uuid_group', "replace(uuid(),'-','')", FALSE);
        $this->db->insert($this->table, $data);

        $datainsert = array(
            'PROCESS' => 'INSERT',
            'id' => $this->db->insert_id()
        );

    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_accounting_group_model.php */
/* Location: ./application/models/Tbl_accounting_group_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-09-24 15:01:18 */
/* http://harviacode.com */